services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DB_HOST
        value: mysql.railway.internal
      - key: DB_PORT
        value: 3306
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: FjyNwxKrZXCIfBcgfthIcqZcLINOlSKt
      - key: DB_NAME
        value: railway
