services:
  - type: web
    name: flask-backend
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python app.py"
    envVars:
      - key: DB_HOST
        value: turntable.proxy.rlwy.net
      - key: DB_PORT
        value: 56167
      - key: DB_USER
        value: root
      - key: DB_PASS
        value: FjyNwxKrZXCIfBcgfthIcqZcLINOlSKt
      - key: DB_NAME
        value: railway
